[package]
name = "tera-hot-reload"
version = "0.2.0"
authors = ["Tebarem"]
edition = "2021"

[dependencies]
tera-template-derive = { path = "./src/tera-template-derive" }
notify-debouncer-full = "0.3.1"
tower-livereload = "0.9.3"