[package]
name = "tera-template-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
tera = { version = "1", default-features = false }
syn = "2.0.72"
quote = "1.0.37"
proc-macro2 = "1.0.86"
[lib]
proc-macro = true
